service: board

package:
  individually: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'ap-northeast-2'}
  environment:
    DYNAMODB_TABLE: Board
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:ap-northeast-2:*:*"

functions:
  create:
    handler: main.handle
    events:
      - http:
          path: /{type}
          cors: true
          method: post

  read:
    handler: main.handle
    events:
      - http:
          path: /{type}/{id}
          cors: true
          method: get
          
  update:
    handler: main.handle
    events:
      - http:
          path: /{type}/{id}
          cors: true
          method: put

  delete:
    handler: main.handle
    events:
      - http:
          path: /{type}/{id}
          cors: true
          method: delete

  getall:
    handler: main.search
    events:
      - http:
          path: /
          cors: true
          method: get

  searchName:
    handler: main.searchoption
    events:
      - http:
          path: /
          cors: true
          method: post

  searchContent:
    handler: main.searchoption
    events:
      - http:
          path: /
          cors: true
          method: post

resources:
  Resources:
    productDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: BoardType
            AttributeType: S
          - AttributeName: BoardId
            AttributeType: S
          - AttributeName: CreateAt
            AttributeType: S
          - AttributeName: Sort
            AttributeType: N
          - AttributeName: BoardName
            AttributeType: S
         
        KeySchema:
          - AttributeName: BoardType
            KeyType: HASH
          - AttributeName: BoardId
            KeyType: RANGE
        
        GlobalSecondaryIndexes:
          - IndexName: BoardIdIndex
            KeySchema:
              - AttributeName: Sort
                KeyType: HASH
              - AttributeName: CreateAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

          - IndexName: NameSearchIndex
            KeySchema:
              - AttributeName: BoardName
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        
          - IndexName: ContentSearchIndex
            KeySchema:
              - AttributeName: Sort
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}